[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2021"

[dependencies]
aoc = { "path" = "aoc" }

[profile.release]
# Enable debug information in release builds.
debug = true
